
total_sales = df['Sales'].sum()
print("Total Sales:", total_sales)
average_sales = df['Sales'].mean()
print("Average Sales:", average_sales)
total_orders = df['Order ID'].nunique()
print("Total Orders:", total_orders)
best_product = df.groupby('Product')['Quantity Ordered'].sum().sort_values(ascending=False)
print("\nBest Selling Product:")
print(best_product.head())
monthly_sales = df.groupby('Month')['Sales'].sum()
print("\nMonthly Sales:")
print(monthly_sales)
city_sales = df.groupby('City')['Sales'].sum().sort_values(ascending=False)
print("\nCity-wise Sales:")
print(city_sales)
highest_month = monthly_sales.idxmax()
highest_value = monthly_sales.max()
print(f"\nHighest Revenue Month: {highest_month}")
print(f"Revenue Generated: {highest_value}")
avg_quantity = df['Quantity Ordered'].mean()
print("\nAverage Quantity Ordered:", avg_quantity)
correlation = df.corr(numeric_only=True)
print("\nCorrelation Matrix:")
print(correlation)